### ISSUE TITLE
As an authenticated user who is playing the game with the "Clouds" game mode, I want to be able to see a satellite image that is covered with "Clouds" so I can find out where I am by wiping off the clouds by holding the left mouse button.

### ISSUE THREAD

**Issue by benlegiang** [sopra-fs21-group-24/client#19]
Acceptance criteria:
- [x] Given the round started, when the user holds the left mouse button and hovers (draws) over the image of the map, then the clouds disappear in a radius around the mouse of the user
- [x] Upon failure, an error message is displayed on what went wrong and a recommendation for the user on what to do

**Comment by JeromeHadorn** [comment]
All the related dev work has been finished for this user story.
