### ISSUE TITLE
As an authenticated user who just beat the highest score on the leaderboard for the corresponding the game mode, I want to see confetti raining down the screen and have a crown symbol next to my entry on the scoreboard component so I feel special.

### ISSUE THREAD

**Issue by benlegiang** [sopra-fs21-group-24/client#20]
Acceptance criteria:
- [x] Given a score after finishing a game, when the score exceeds the current high score, then confetti rains down on the user's screen
- [x] Given a score after finishing a game, when the score exceeds the current high score, then a crown symbol is put next to the user's username on the scoreboard component
- [x] Upon failure, no celebratory actions is taking place or the user is informed that there was an error when adding their score to the scoreboard

Estimate: 2h

**Comment by JeromeHadorn** [comment]
All related work for this story is tested & completed
