### ISSUE TITLE
Create scoreboard component on home screen

### ISSUE THREAD

**Issue by benlegiang** [sopra-fs21-group-24/client#28]
Estimate: 3h

This is part of user story #6 

Acceptance criteria:

-  [ ] Given I am on the home screen i want to be able to see the scoreboard filled with the best player scores
-  [ ] When I look at the scoreboard I want to be able to chose for which game mode I want to see the scoreboard
-  [ ] Upon failure, an error is displayed at the spot where the scoreboard should be

**Comment by claudioge** [comment]
Acceptance criteria:
- [ ] Given I am on the home screen i want to be able to see the scoreboard filled with the best player scores
- [ ] When I look at the scoreboard I want to be able to chose for which game mode I want to see the scoreboard
- [ ] Upon failure, an error is displayed at the spot where the scoreboard should be
