### ISSUE TITLE
Display satellite image covered with clouds for game mode "Clouds" on game page

### ISSUE THREAD

**Issue by benlegiang** [sopra-fs21-group-24/client#48]
Estimate: 3h

This is part of user story #19

Acceptance criteria:
- [ ] Given I chose to play the clouds game mode I want to see satellite picture covered in clouds
- [ ] Upon failure, an error message is displayed and the game is exited prematurely

**Comment by claudioge** [comment]
Acceptance criteria:
- [ ] Given I chose to play the clouds game mode I want to see satellite picture covered in clouds
- [ ] Upon failure, an error message is displayed and the game is exited prematurely
