### ISSUE TITLE
Implement eraser feature (hold left mouse button) for game mode "Clouds" 

### ISSUE THREAD

**Issue by benlegiang** [sopra-fs21-group-24/client#49]
Estimate: 2h

This is part of user story #19 

Acceptance criteria:

- [ ] Given I press my left mouse button I want to see the clouds slowly disappearing
- [ ] Upon failure, an error message is shown and the game is exited prematurely, because the game would be unplayable

**Comment by claudioge** [comment]
Acceptance criteria:
- [ ] Given I press my left mouse button I want to see the clouds slowly disappearing 
- [ ] Upon failure, an error message is shown and the game is exited prematurely, because the game would be unplayable
