### ISSUE TITLE
Implement confetti celebration and crown symbol for new high score

### ISSUE THREAD

**Issue by benlegiang** [sopra-fs21-group-24/client#50]
Estimate: 3h

This is part of user story #20 

Acceptance Criteria:
- [ ] Confetti should rain down the screen if you've won the game
- [ ] Confetti starts when everyone submitted their guess
- [ ] Confetti stops when exiting the game

**Comment by claudioge** [comment]
Acceptance criteria:
- [ ] Given I beat my highscore i want to see confetti celebration on the screen
- [ ] Upon failure, the highscore is updated and no celebration is displayed
