### ISSUE TITLE
As an authenticated user, I want to see a scoreboard of the 15 best players with their names and achieved score for each game mode to form an opinion on how good or bad I am relative to other users and whether I made it onto the scoreboard

### ISSUE THREAD

**Issue by benlegiang** [sopra-fs21-group-24/client#6]
Acceptance criteria:
- [x] Given being logged in, when the user is on the home screen, then a scoreboard of the 15 best players with their names and scores is displayed and updated as new high scores are achieved
- [x] Upon failure, the scoreboard component should be replaced by an error message showing that the scoreboard could not be loaded

Estimate: 3h

**Comment by JeromeHadorn** [comment]
All dev work has been completed.
